image: "rust:latest"

variables:
  GIT_DEPTH: 100
  RBBT_URL: https://gitlab.com/rcook/rbbt/-/raw/v0.4/rbbt

before_script:
  - echo $RBBT_URL
  - curl $RBBT_URL | bash -s -- --remote origin --ref $CI_COMMIT_REF_NAME

.shared: &shared
  except:
    refs:
      - /^.+-no-ci$/
      - /^.+-no-gitlab-ci$/

build:cargo:
  <<: *shared
  script:
    - rustc --version && cargo --version
    - cargo clean
    - cargo build
    - cargo build --release
  artifacts:
    paths:
      - target/debug/rws
      - target/release/rws

test:cargo:
  <<: *shared
  script:
    - rustc --version && cargo --version
    - cargo test --all --verbose
