image: "rust:latest"

variables:
  GIT_DEPTH: 100

before_script:
  - curl https://gitlab.com/rcook/rbbt/-/raw/v0.1/rbbt-cargo | bash

.shared: &shared
  except:
    refs:
      - /^.+-no-ci$/

build:cargo:
  <<: *shared
  script:
    - rustc --version && cargo --version
    - cargo clean
    - cargo build
    - cargo build --release
  artifacts:
    paths:
      - target/debug/rws
      - target/release/rws

test:cargo:
  <<: *shared
  script:
    - rustc --version && cargo --version
    - cargo clean
    - cargo test --all --verbose
