environment:
  RBBT_URL: https://gitlab.com/rcook/rbbt/-/raw/v0.3/rbbt
  CHANNEL: nightly
  global:
    PROJECT_NAME: rws
  matrix:
    - TARGET: x86_64-pc-windows-msvc
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS
      TARGET: x86_64-apple-darwin
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      TARGET: x86_64-unknown-linux-gnu

install:
  - sh: echo $RBBT_URL
  - sh: curl $RBBT_URL | bash -s -- --branch $APPVEYOR_REPO_BRANCH
  - sh: cat .rbbt_version
  - ps: if ($env:CI_WINDOWS -ne 'true') { Update-AppveyorBuild -Version (Get-Content -Path .rbbt_version -Raw).Trim() }
  - sh: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-host $TARGET --default-toolchain $CHANNEL --profile minimal -y
  - sh: source $HOME/.cargo/env
  - sh: rustc -Vv
  - sh: cargo --version
  - cmd: echo %RBBT_URL%
  - cmd: appveyor-retry appveyor DownloadFile %RBBT_URL%.ps1
  - ps: if ($env:CI_WINDOWS -eq 'true') { .\rbbt.ps1 -Branch $env:APPVEYOR_REPO_BRANCH }
  - ps: if ($env:CI_WINDOWS -eq 'true') { Get-Content -Path .rbbt_version }
  - ps: if ($env:CI_WINDOWS -eq 'true') { Update-AppveyorBuild -Version (Get-Content -Path .rbbt_version -Raw).Trim() }
  - cmd: appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - cmd: set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - cmd: rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% --profile minimal -y
  - cmd: rustc -Vv
  - cmd: cargo --version

build: false

build_script:
  - cargo clean
  - cargo build
  - cargo build --release

test_script:
  - cargo test --all --verbose

artifacts:
  - path: target/debug/rws
  - path: target/debug/rws.exe
  - path: target/release/rws
  - path: target/release/rws.exe

branches:
  except:
    - /^.+-no-ci$/
    - /^.+-no-appveyor-ci$/
