# https://github.com/japaric/rust-everywhere/blob/master/appveyor.yml
# https://github.com/rust-lang/libc/blob/master/appveyor.yml
# https://github.com/rust-lang/rustfmt/blob/master/appveyor.yml

branches:
  except:
    - /^.+-no-ci$/
    - /^.+-no-appveyor-ci$/

environment:
  RBBT_URL: https://gitlab.com/rcook/rbbt/-/raw/v0.2.1/rbbt-cargo.ps1
  global:
    PROJECT_NAME: rws
  matrix:
    # Stable channel
    # - TARGET: i686-pc-windows-gnu
    #   CHANNEL: stable
    # - TARGET: i686-pc-windows-msvc
    #   CHANNEL: stable
    # - TARGET: x86_64-pc-windows-gnu
    #   CHANNEL: stable
    # - TARGET: x86_64-pc-windows-msvc
    #   CHANNEL: stable
    # Beta channel
    # - TARGET: i686-pc-windows-gnu
    #   CHANNEL: beta
    # - TARGET: i686-pc-windows-msvc
    #   CHANNEL: beta
    # - TARGET: x86_64-pc-windows-gnu
    #   CHANNEL: beta
    # - TARGET: x86_64-pc-windows-msvc
    #   CHANNEL: beta
    # Nightly channel
#    - TARGET: i686-pc-windows-gnu
#      CHANNEL: nightly
#    - TARGET: i686-pc-windows-msvc
#      CHANNEL: nightly
#    - TARGET: x86_64-pc-windows-gnu
#      CHANNEL: nightly
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: nightly

install:
  - echo %RBBT_URL%
  - appveyor-retry appveyor DownloadFile %RBBT_URL%
  - ps: .\rbbt-cargo.ps1
  - ps: Update-AppveyorBuild -Version (Get-Content -Path .rbbt_version -Raw).Trim()
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - if "%TARGET%" == "i686-pc-windows-gnu" set PATH=%PATH%;C:\msys64\mingw32\bin
  - if "%TARGET%" == "x86_64-pc-windows-gnu" set PATH=%PATH%;C:\msys64\mingw64\bin
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% --profile minimal -y
  - rustc -Vv
  - cargo -V

# ???
build: false

build_script:
  - rustc --version && cargo --version
  - cargo clean
  - cargo build
  - cargo build --release

test_script:
  - rustc --version && cargo --version
  - cargo test --all --verbose

artifacts:
  - path: target/debug/rws.exe
  - path: target/release/rws.exe
