[package]
name = "rws"
version = "0.0.0"
description = "Development"
authors = ["Richard Cook <rcook@rcook.org>"]
edition = "2018"

[dependencies]
absolute-path = { git = "https://github.com/rcook/absolute-path.git", rev = "aca86cfb77bfea08632d1fe49a61092a19a10310" }
clap = "2.33.0"
colored = "1.9.3"
dirs = "2.0.2"
gc = "0.3.3"
git2 = { path = "git2-rs" }
percent-encoding = "2.1.0"
regex = "1.3.5"
rlua = "0.17.0"
sxd-document = "0.3.2"
sxd-xpath = "0.4.2"
tempfile = "3.1.0"
topological-sort = "0.1.0"
which = "3.1.1"
yaml-rust = "0.4"
