#!/bin/bash
set -euo pipefail

this_dir=$(cd $(dirname $0); pwd -P)

cd $this_dir
cargo build
cargo build --release
cargo test
cargo test --release
cargo clippy --all-targets --all-features -- -D warnings
