name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 5 * * *

jobs:
  ci:
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc
          - x86_64-unknown-linux-gnu
        include:
          - target: x86_64-apple-darwin
            build_os: macos-latest
          - target: x86_64-pc-windows-msvc
            build_os: windows-latest
          - target: x86_64-unknown-linux-gnu
            build_os: ubuntu-latest
    runs-on: ${{ matrix.build_os }}
    steps:
      - name: Set up environment
        shell: bash
        run: |
          if [ '${{ matrix.build_os }}' == 'windows-latest' ]; then
            # MinGW perl doesn't handle Windows paths properly
            echo '/C/Strawberry/perl/bin' >> $GITHUB_PATH
            mv /usr/bin/perl /usr/bin/perl.bak
          fi

      - name: Build and test Rust package
        uses: rcook/rust-package-action@v0.0.3
        with:
          target: ${{ matrix.target }}
